[package]
name = "rhizome"
version = "0.1.0"
authors = ["romatthe"]

[dependencies]
arrayvec = "0.3.23"
bincode = "0.8.0"
byteorder = "1.1.0"
rand = "0.3.15"
serde = "1.0.10"
serde_derive = "1.0.10"
sha1 = "0.2.0"